apiVersion: apps/v1
kind: Deployment
metadata:
  name: avitraining03162023
spec:
  selector:
    matchLabels:
      app: avitraining03162023
  template:
    metadata:
      labels:
        app: avitraining03162023
    spec:
      containers:
      - name: avitraining03162023
        image: sbacr02.azurecr.io/avitraining_assessment_03162023:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5296
